"""empty message

Revision ID: 2649a5a0e479
Revises: f4ee22e6bd6c
Create Date: 2023-12-04 23:37:22.169731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2649a5a0e479'
down_revision = 'f4ee22e6bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
