"""empty message

Revision ID: 2b30c0bc332e
Revises: 7bbde5f9c87d
Create Date: 2023-12-17 23:13:38.567186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b30c0bc332e'
down_revision = '7bbde5f9c87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
