"""empty message

Revision ID: 2da66d124ff5
Revises: ccc4a7252fa0
Create Date: 2023-12-14 18:06:58.644826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da66d124ff5'
down_revision = 'ccc4a7252fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.alter_column('turn',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.alter_column('turn',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
