"""all settings for post

Revision ID: 3635e9bb6e9d
Revises: bd416485a043
Create Date: 2023-12-03 11:11:14.532289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3635e9bb6e9d'
down_revision = 'bd416485a043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('picture')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
