"""empty message

Revision ID: 42124a9d0a47
Revises: c4142dc028bc
Create Date: 2023-12-12 18:54:25.058117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42124a9d0a47'
down_revision = 'c4142dc028bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room__members', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room__members', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
