"""60 now to fit hashed pw

Revision ID: 556082065029
Revises: 2ac3d6de06e5
Create Date: 2023-12-03 03:01:25.758441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556082065029'
down_revision = '2ac3d6de06e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
