"""empty message

Revision ID: 56dd7e96b563
Revises: 1002d5aea6d1
Create Date: 2023-12-12 21:54:21.083886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56dd7e96b563'
down_revision = '1002d5aea6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room__members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room__members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
