"""empty message

Revision ID: 76e9d09ec370
Revises: 2649a5a0e479
Create Date: 2023-12-05 00:03:42.983450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e9d09ec370'
down_revision = '2649a5a0e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_mimetype', sa.Text(), nullable=True))
        batch_op.alter_column('picture',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('picture_mimetype')

    # ### end Alembic commands ###
