"""empty message

Revision ID: 7bbde5f9c87d
Revises: 1167c65a1f18
Create Date: 2023-12-17 22:54:57.458631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbde5f9c87d'
down_revision = '1167c65a1f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
