"""empty message

Revision ID: b411ac696e4a
Revises: 62a5d10917a9
Create Date: 2023-12-15 08:20:07.312051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b411ac696e4a'
down_revision = '62a5d10917a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adlib_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adlib_post', schema=None) as batch_op:
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
