"""empty message

Revision ID: c1e844bf1d3d
Revises: 7a7de79fc184
Create Date: 2023-12-10 16:43:41.689574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e844bf1d3d'
down_revision = '7a7de79fc184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stream')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('stream')

    # ### end Alembic commands ###
