"""empty message

Revision ID: c517e52c8e48
Revises: a2ef0f2c4199
Create Date: 2023-12-12 16:15:30.107957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c517e52c8e48'
down_revision = 'a2ef0f2c4199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members', sa.String(length=100), nullable=True))
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('members')

    # ### end Alembic commands ###
