"""empty message

Revision ID: d9de2be72a65
Revises: 42124a9d0a47
Create Date: 2023-12-12 21:22:10.607967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9de2be72a65'
down_revision = '42124a9d0a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game__room__messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=4), nullable=False),
    sa.Column('member_message', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game__room__messages')
    # ### end Alembic commands ###
