"""empty message

Revision ID: e3e6ed4e00ac
Revises: c9ac90f2c53c
Create Date: 2023-12-11 09:46:11.665597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e6ed4e00ac'
down_revision = 'c9ac90f2c53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game__room', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
