"""empty message

Revision ID: e4865bdce05c
Revises: d70a169de78c
Create Date: 2023-12-15 09:10:44.004488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4865bdce05c'
down_revision = 'd70a169de78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adlib_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adlib_post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
